### ISSUE TITLE
Домашка №0, которую и так все сделали

### ISSUE THREAD

**Issue by tiny-kottan** [dimavel/kottans-homework#1]
1. Установить git / ознакомиться с ним
2. IDE/editor, ознакомиться с ним.
3. DevTools - пройти на CodeSchool (http://discover-devtools.codeschool.com/).
4. Github - завести репозитарий для домашек.
5. GitBranching: http://pcottle.github.io/learnGitBranching/ пройти Main, забросить скриншот в гитхаб, сюда запостить ссылку

**Comment by dima-zhuravel** [comment]
[Lesson#0 git screen](https://github.com/dimavel/kottans-homework/blob/master/Lesson%230.jpg)

**Comment by sudodoki** [comment]
👍
